# TPU Training Configuration
data_path: "gs://your-mimic-bucket-name/processed_data"
data_type: "parquet"
output_dir: "gs://your-mimic-bucket-name/models"

# Data parameters
patient_id_col: "subject_id"
time_col: "window_end"
window_size: 48
stride: 12
normalize: true
impute_method: "forward_fill"

# Model parameters
encoder_hidden_dim: 256
encoder_latent_dim: 128
context_hidden_dim: 256
prediction_hidden_dim: 128
prediction_steps: 12
temperature: 0.07

# Training parameters
batch_size: 512  # TPUs can handle much larger batches
num_epochs: 100
learning_rate: 0.001
weight_decay: 0.00001
lr_factor: 0.5
lr_patience: 10
save_every: 5
warmup_steps: 1000
decay_steps: 100000
use_learning_rate_schedule: true
gradient_clip: 1.0

# TPU-specific parameters
use_tpu: true
tpu_cores: 8
precision: "bfloat16"

# GCS-specific parameters
use_gcs: true
gcs_bucket: "your-mimic-bucket-name"  # Will be overridden by GCS_BUCKET env var
